version: '3'

services:
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: php-mysqli-enabled.dockerfile
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - "80:80"